routes/web.php
<?php

use App\Category;
use App\Department;
use App\Inventory;
use App\Member;
use App\Procurement;
use App\Supplier;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::resource("departments","DepartmentController");
Route::resource("suppliers","SupplierController");
Route::resource("members","MemberController");
Route::resource("categories","CategoryController");
Route::resource("procurements","ProcurementController");
Route::resource("inventories","InventoryController");
Route::resource("mutations","MutationController");
Route::resource("reports","ReportController");
Route::get('allassetlistreport', 'AllAssetListReportController@index')->name('allassetlistreport');
Route::get('supplierlistreport', 'SupplierListReportController@index')->name('supplierlistreport');
Route::get('memberlistreport', 'MemberListReportController@index')->name('memberlistreport');
Route::get('assetmutationreport', 'AssetMutationReportController@index')->name('assetmutationreport');
Route::get('assetscrappingreport', 'AssetScrappingReportController@index')->name('assetscrappingreport');
Route::get('assetbalancereport', 'AssetBalanceReportController@index')->name('assetbalancereport');
Route::get('specialassetbasedontypeofmobilityreport', 'SpecialAssetBasedOnTypeOfMobilityReportController@index')->name('specialassetbasedontypeofmobilityreport');
Route::resource("outgoings","OutgoingController"); // Add this line in routes.php

/*
    ___       _____   _  __
   /   |     / /   | | |/ /
  / /| |__  / / /| | |   / 
 / ___ / /_/ / ___ |/   |  
/_/  |_\____/_/  |_/_/|_|  
                           
*/

Route::get('/getAll', function() {

	$inventories = Inventory::all();

	$return = array(
'records' => $inventories,
'query_record_count' => sizeof($inventories),
'total_record_count' => sizeof($inventories)
		);
	// dd($car[0]->store_id);
   return $inventories;
});

Route::get('/getDepartment', function() {

	$departments = Department::all();

	;
	// dd($car[0]->store_id);
   return $departments;
});


Route::get('/getSupplier', function() {

	$suppliers = Supplier::all();

	;
	// dd($car[0]->store_id);
   return $suppliers;
});

Route::get('/getMember', function() {

	$members = Member::all();

	;
	// dd($car[0]->store_id);
   return $members;
});

Route::get('/getCategory', function() {

	$categories = Category::all();

	;
	// dd($car[0]->store_id);
	// dd($categories);
   return $categories;
});

Route::get('/getMobility', function() {

	$mobilities = 
collect(['low'=>'Low','medium'=>'Medium','high'=>'High']);
	// Category::all();

	;
	// dd($mobilities);
	// dd($car[0]->store_id);
   return $mobilities;
});


Route::get('/getProcurement', function() {

	$procurements = Procurement::all();

	;
	// dd($car[0]->store_id);
   return $procurements;
});

app/Mutation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mutation extends Model
{
    public function detail()
    {
        return $this->hasOne('App\MutationDetail', 'mutation_id', 'id');
    }
}

app/Http/Controllers/MutationController.php
<?php namespace App\Http\Controllers;

use App\Department;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Inventory;
use App\Member;
use App\Mutation;
use App\MutationDetail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MutationController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$mutations = Mutation::orderBy('id', 'desc')->paginate(10);

		return view('mutations.index', compact('mutations'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$inventory = Inventory::pluck('assets_number','id');
		$department = Department::pluck('name','id')->prepend('Please Select','');
		$member = Member::pluck('name','id')->prepend('Please Select','');
		return view('mutations.create',compact('inventory','department','member'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$mutation = new Mutation();

		$mutation->keterangan = $request->input("keterangan");
        $mutation->tanggal_mutasi = $request->input("tanggal_mutasi");
        $mutation->nomor_pma = $request->input("nomor_pma");
		$mutation->save();

		$id = $mutation->id;

		foreach ($request->input("inventories") as $value) {
			
			DB::table('mutations_detail')->insert(
			    [
			    'mutation_id' => $id,
			    'inventory_id' => $value,
			    'department_from' => $request->input("department_from"),
			    'department_to' => $request->input("department_to"),
			    'user_from' => $request->input("user_from"),
			    'user_to' => $request->input("user_to")
			    ]
			);
			$inventory = Inventory::findOrFail($value);
	        $inventory->department_id = $request->input("department_to");
	        $inventory->user_id = $request->input("user_to");
	        $inventory->save();
	        
		}

		return redirect()->route('mutations.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$mutation = Mutation::findOrFail($id);
		$details = MutationDetail::where('mutation_id', $id)
               ->get();
        $_department_to = $details[0]->department_to;
		$_department_from = $details[0]->department_from;
		$_user_to = $details[0]->user_to;
        $_user_from = $details[0]->user_from;
        
        $department_to = Department::findOrFail($_department_to);
		$department_from = Department::findOrFail($_department_from);
        $user_to = Member::findOrFail($_user_to);
        $user_from = Member::findOrFail($_user_from);

        $array = [
        'dept_to' => $department_to->name,
        'dept_from' => $department_from->name,
        'user_to' => $user_to->name,
        'user_from' => $user_from->name
        ];




		return view('mutations.show', compact('mutation','details','array'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$mutation = Mutation::findOrFail($id);

		return view('mutations.edit', compact('mutation'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$mutation = Mutation::findOrFail($id);

		$mutation->keterangan = $request->input("keterangan");
        $mutation->tanggal_mutasi = $request->input("tanggal_mutasi");

		$mutation->save();

		return redirect()->route('mutations.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$mutation = Mutation::findOrFail($id);
		$mutation->delete();

		return redirect()->route('mutations.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/mutations/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Mutations / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('mutations.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('keterangan')) has-error @endif">
                       <label for="keterangan-field">NOTES</label>
                    <textarea class="form-control" id="keterangan-field" rows="3" name="keterangan">{{ old("keterangan") }}</textarea>
                       @if($errors->has("keterangan"))
                        <span class="help-block">{{ $errors->first("keterangan") }}</span>
                       @endif
                    </div>

                <div class="form-group @if($errors->has('nomor_pma')) has-error @endif">
                    <label for="nomor_pma-field">PMA Number</label>
                    <input type="text" id="nomor_pma-field" name="nomor_pma" class="form-control" value="{{ old("nomor_pma") }}"/>
                    @if($errors->has("nomor_pma"))
                        <span class="help-block">{{ $errors->first("nomor_pma") }}</span>
                    @endif
                </div>

                    <div class="form-group @if($errors->has('tanggal_mutasi')) has-error @endif">
                       <label for="tanggal_mutasi-field">Mutation Date</label>
                    <input type="text" id="tanggal_mutasi-field" name="tanggal_mutasi" class="form-control date-picker" value="{{ old("tanggal_mutasi") }}"/>
                       @if($errors->has("tanggal_mutasi"))
                        <span class="help-block">{{ $errors->first("tanggal_mutasi") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('department_from')) has-error @endif">
                       <label for="department_from-field">department_from</label>
                       {!! Form::select('department_from', $department,old("department_from"),['class' => 'form-control','id'=>'department_from-field']); !!}
                       @if($errors->has("department_from"))
                        <span class="help-block">{{ $errors->first("department_from") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('user_from')) has-error @endif">
                       <label for="user_from-field">user_from</label>
                       {!! Form::select('user_from', $member,old("user_from"),['class' => 'form-control','id'=>'user_from-field']); !!}
                       @if($errors->has("user_from"))
                        <span class="help-block">{{ $errors->first("user_from") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('department_from')) has-error @endif">
                       <label for="department_from-field">department_from</label>
                       {!! Form::select('department_from', $department,old("department_from"),['class' => 'form-control','id'=>'department_from-field']); !!}
                       @if($errors->has("department_from"))
                        <span class="help-block">{{ $errors->first("department_from") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('user_to')) has-error @endif">
                       <label for="user_to-field">user_to</label>
                       {!! Form::select('user_to', $member,old("user_to"),['class' => 'form-control','id'=>'user_to-field']); !!}
                       @if($errors->has("user_to"))
                        <span class="help-block">{{ $errors->first("user_to") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('department_to')) has-error @endif">
                       <label for="department_to-field">department_to</label>
                       {!! Form::select('department_to', $department,old("department_to"),['class' => 'form-control','id'=>'department_to-field']); !!}
                       @if($errors->has("department_to"))
                        <span class="help-block">{{ $errors->first("department_to") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('inventories')) has-error @endif">
                       <label for="inventories-field">Inventories</label>
                       {!! Form::select('inventories[]', $inventory,old("inventories"),['class' => 'form-control','class'=>'js-example-basic-multiple','multiple'=>'multiple' ,'id'=>'inventories-field']); !!}
                       @if($errors->has("inventories"))
                        <span class="help-block">{{ $errors->first("inventories") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('mutations.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  x  <script>
    $('.date-picker').datepicker({
      format: 'yyyy-mm-dd',
      todayHighlight: true
    });
  </script>
  <script type="text/javascript">
$(".js-example-basic-multiple").select2(
  {
    placeholder: "Select a Inventories, don't duplicate",
    dropdownAutoWidth : true,
    width: '100%',
    tags: true,
  tokenSeparators: [',', ' ']
  });
</script>
@endsection

resources/views/mutations/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Mutations / Edit #{{$mutation->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('mutations.update', $mutation->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('keterangan')) has-error @endif">
                       <label for="keterangan-field">Notes</label>
                    <textarea class="form-control" id="keterangan-field" rows="3" name="keterangan">{{ is_null(old("keterangan")) ? $mutation->keterangan : old("keterangan") }}</textarea>
                       @if($errors->has("keterangan"))
                        <span class="help-block">{{ $errors->first("keterangan") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('tanggal_mutasi')) has-error @endif">
                       <label for="tanggal_mutasi-field">Mutation Date</label>
                    <input type="text" id="tanggal_mutasi-field" name="tanggal_mutasi" class="form-control date-picker" value="{{ is_null(old("tanggal_mutasi")) ? $mutation->tanggal_mutasi : old("tanggal_mutasi") }}"/>
                       @if($errors->has("tanggal_mutasi"))
                        <span class="help-block">{{ $errors->first("tanggal_mutasi") }}</span>
                       @endif
                    </div>

                <div class="form-group @if($errors->has('nomor_pma')) has-error @endif">
                    <label for="nomor_pma-field">PMA Number</label>
                    <input type="text" id="nomor_pma-field" name="nomor_pma" class="form-control" value="{{ is_null(old("nomor_pma")) ? $mutation->nomor_pma : old("nomor_pma") }}"/>
                    @if($errors->has("nomor_pma"))
                        <span class="help-block">{{ $errors->first("nomor_pma") }}</span>
                    @endif
                </div>

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('mutations.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
      format: 'yyyy-mm-dd',
      todayHighlight: true
    });
  </script>
@endsection

resources/views/mutations/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Mutations
            <a class="btn btn-success pull-right" href="{{ route('mutations.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($mutations->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NOTES</th>
                            <th>MUTATION DATE</th>
                            <th>PMA NUMBER</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($mutations as $mutation)
                            <tr>
                                <td>{{$mutation->id}}</td>
                                <td>{{$mutation->keterangan}}</td>
                                <td>{{$mutation->tanggal_mutasi}}</td>
                                <td>{{$mutation->nomor_pma}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('mutations.show', $mutation->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    {{-- <a class="btn btn-xs btn-warning" href="{{ route('mutations.edit', $mutation->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a> --}}
                                    {{--<form action="{{ route('mutations.destroy', $mutation->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>--}}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $mutations->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/mutations/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Mutations / Show #{{$mutation->id}}</h1>
        {{--<form action="{{ route('mutations.destroy', $mutation->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                --}}{{-- <a class="btn btn-warning btn-group" role="group" href="{{ route('mutations.edit', $mutation->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a> --}}{{--
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>--}}
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                     <label for="keterangan">KETERANGAN</label>
                     <p class="form-control-static">{{$mutation->keterangan}}</p>
                </div>
                    <div class="form-group">
                     <label for="tanggal_mutasi">TANGGAL_MUTASI</label>
                     <p class="form-control-static">{{$mutation->tanggal_mutasi}}</p>
                </div>
                <div class="form-group">
                    <label for="tanggal_mutasi">NOMOR_PMA</label>
                    <p class="form-control-static">{{$mutation->nomor_pma}}</p>
                </div>
                <div class="form-group">
                     <label for="tanggal_mutasi">Departmen from</label>
                     <p class="form-control-static">{{$array['dept_from']}}</p>
                </div>
                <div class="form-group">
                     <label for="tanggal_mutasi">Department_to</label>
                     <p class="form-control-static">{{$array['dept_to']}}</p>
                </div>
                <div class="form-group">
                     <label for="tanggal_mutasi">User from</label>
                     <p class="form-control-static">{{$array['user_from']}}</p>
                </div>
                <div class="form-group">
                     <label for="tanggal_mutasi">User to</label>
                     <p class="form-control-static">{{$array['user_to']}}</p>
                </div>
                <div class="form-group">
                     <label for="keterangan">List of Inventories</label>
                     @foreach ($details as $detail)
                    <p>{{ $detail->inv->name }}</p>
                    @endforeach
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('mutations.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection