routes/web.php
<?php

use App\Category;
use App\Department;
use App\Inventory;
use App\Member;
use App\Procurement;
use App\Supplier;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::resource("departments","DepartmentController");
Route::resource("suppliers","SupplierController");
Route::resource("members","MemberController");
Route::resource("categories","CategoryController");
Route::resource("procurements","ProcurementController");
Route::resource("inventories","InventoryController");
Route::resource("mutations","MutationController");
Route::resource("reports","ReportController");
Route::get('allassetlistreport', 'AllAssetListReportController@index')->name('allassetlistreport');
Route::get('supplierlistreport', 'SupplierListReportController@index')->name('supplierlistreport');
Route::get('memberlistreport', 'MemberListReportController@index')->name('memberlistreport');
Route::get('assetmutationreport', 'AssetMutationReportController@index')->name('assetmutationreport');
Route::get('assetscrappingreport', 'AssetScrappingReportController@index')->name('assetscrappingreport');
Route::get('assetbalancereport', 'AssetBalanceReportController@index')->name('assetbalancereport');
Route::get('specialassetbasedontypeofmobilityreport', 'SpecialAssetBasedOnTypeOfMobilityReportController@index')->name('specialassetbasedontypeofmobilityreport');
Route::resource("outgoings","OutgoingController"); // Add this line in routes.php

/*
    ___       _____   _  __
   /   |     / /   | | |/ /
  / /| |__  / / /| | |   / 
 / ___ / /_/ / ___ |/   |  
/_/  |_\____/_/  |_/_/|_|  
                           
*/

Route::get('/getAll', function() {

	$inventories = Inventory::all();

	$return = array(
'records' => $inventories,
'query_record_count' => sizeof($inventories),
'total_record_count' => sizeof($inventories)
		);
	// dd($car[0]->store_id);
   return $inventories;
});

Route::get('/getDepartment', function() {

	$departments = Department::all();

	;
	// dd($car[0]->store_id);
   return $departments;
});


Route::get('/getSupplier', function() {

	$suppliers = Supplier::all();

	;
	// dd($car[0]->store_id);
   return $suppliers;
});

Route::get('/getMember', function() {

	$members = Member::all();

	;
	// dd($car[0]->store_id);
   return $members;
});

Route::get('/getCategory', function() {

	$categories = Category::all();

	;
	// dd($car[0]->store_id);
	// dd($categories);
   return $categories;
});

Route::get('/getMobility', function() {

	$mobilities = 
collect(['low'=>'Low','medium'=>'Medium','high'=>'High']);
	// Category::all();

	;
	// dd($mobilities);
	// dd($car[0]->store_id);
   return $mobilities;
});


Route::get('/getProcurement', function() {

	$procurements = Procurement::all();

	;
	// dd($car[0]->store_id);
   return $procurements;
});

app/Inventory.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    public function dept()
    {
    	return $this->hasOne('App\Department', 'id', 'department_id');
    }
    public function supp()
    {
    	return $this->hasOne('App\Supplier', 'id', 'supplier_id');
    }
    public function proc()
    {
    	return $this->hasOne('App\Procurement', 'id', 'procurement_id');
    }
    public function cat()
    {
    	return $this->hasOne('App\Category', 'id', 'category_id');
    }
    public function member()
    {
    	return $this->hasOne('App\Member', 'id', 'user_id');
    }
}

app/Http/Controllers/InventoryController.php
<?php namespace App\Http\Controllers;

use App\Category;
use App\Department;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Inventory;
use App\Member;
use App\Procurement;
use App\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class InventoryController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$inventories = Inventory::where('status',1)->orderBy('id', 'desc')->paginate(10);

		return view('inventories.index', compact('inventories'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$department = Department::pluck('name','id');
		$procurement = Procurement::pluck('name','id');
		$supplier = Supplier::pluck('name','id');
		$category = Category::pluck('name','id');
		$member = Member::pluck('name','id');

		$life = array(2=>2 , 4=>4,8=>8,16=>16);
		return view('inventories.create',compact('department','procurement','supplier','category','member','life'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$inventory = new Inventory();

		$inventory->name = $request->input("name");
        $inventory->description = $request->input("description");
        $inventory->harga_beli = $request->input("harga_beli");
        $inventory->tanggal_beli = $request->input("tanggal_beli");
        $inventory->supplier_id = $request->input("supplier_id");
        $inventory->procurement_id = $request->input("procurement_id");
        $inventory->category_id = $request->input("category_id");
        $inventory->mobility_type = $request->input("mobility_type");
        $inventory->department_id = $request->input("department_id");
        $inventory->user_id = $request->input("user_id");
        $inventory->life = $request->input("life");
        $inventory->keterangan = $request->input("keterangan");
        
        $cat_keyword = DB::table('categories')->where('id',$request->input('category_id'))->get();
        $cat_character = $cat_keyword[0]->name;
        $cat_character = $cat_character[0];

        $maxid = DB::table('inventories')->where('id', DB::raw("(select max(id) from inventories)"))->get();
		if(sizeof( $maxid)==0)
		{
			$maxid =0;
		}
		else
		{
			$maxid = $maxid[0]->id;
		}
		
		$increment = str_pad($maxid + 1, 6, 0, STR_PAD_LEFT);
		$inventory->assets_number = $cat_character.$increment;
		$inventory->save();

		return redirect()->route('inventories.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$inventory = Inventory::findOrFail($id);

		return view('inventories.show', compact('inventory'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$inventory = Inventory::findOrFail($id);

		$department = Department::pluck('name','id');
		$procurement = Procurement::pluck('name','id');
		$supplier = Supplier::pluck('name','id');
		$category = Category::pluck('name','id');
		$member = Member::pluck('name','id');
        $life = array(2=>2 , 4=>4,8=>8,16=>16);

        return view('inventories.edit', compact('inventory','department','procurement','supplier','category','member','life'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$inventory = Inventory::findOrFail($id);

		$inventory->name = $request->input("name");
        $inventory->description = $request->input("description");
        $inventory->harga_beli = $request->input("harga_beli");
        $inventory->tanggal_beli = $request->input("tanggal_beli");
        $inventory->supplier_id = $request->input("supplier_id");
        $inventory->procurement_id = $request->input("procurement_id");
        $inventory->mobility_type = $request->input("mobility_type");
        $inventory->category_id = $request->input("category_id");
        $inventory->department_id = $request->input("department_id");
        $inventory->user_id = $request->input("user_id");
        $inventory->life = $request->input("life");
        $inventory->keterangan = $request->input("keterangan");
        // $inventory->assets_number = $request->input("assets_number");

		$inventory->save();

		return redirect()->route('inventories.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$inventory = Inventory::findOrFail($id);
		$inventory->delete();

		return redirect()->route('inventories.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/inventories/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Inventories / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('inventories.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('description')) has-error @endif">
                       <label for="description-field">Description</label>
                    <input type="text" id="description-field" name="description" class="form-control" value="{{ old("description") }}"/>
                       @if($errors->has("description"))
                        <span class="help-block">{{ $errors->first("description") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('harga_beli')) has-error @endif">
                       <label for="harga_beli-field">Buy Value</label>
                    <input type="number" id="harga_beli-field" name="harga_beli" class="form-control" value="{{ old("harga_beli") }}"/>
                       @if($errors->has("harga_beli"))
                        <span class="help-block">{{ $errors->first("harga_beli") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('tanggal_beli')) has-error @endif">
                       <label for="tanggal_beli-field">Purchase Date</label>
                    <input type="text" id="tanggal_beli-field" name="tanggal_beli" class="form-control date-picker" value="{{ old("tanggal_beli") }}"/>
                       @if($errors->has("tanggal_beli"))
                        <span class="help-block">{{ $errors->first("tanggal_beli") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('supplier_id')) has-error @endif">
                       <label for="supplier_id-field">Supplier_id</label>
                       {!! Form::select('supplier_id', $supplier,old("supplier_id"),['class' => 'form-control','id'=>'supplier_id-field']) !!}
                       @if($errors->has("supplier_id"))
                        <span class="help-block">{{ $errors->first("supplier_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('procurement_id')) has-error @endif">
                       <label for="procurement_id-field">Procurement_id</label>
                       {!! Form::select('procurement_id', $procurement,old("procurement_id"),['class' => 'form-control','id'=>'procurement_id-field']) !!}
                       @if($errors->has("procurement_id"))
                        <span class="help-block">{{ $errors->first("procurement_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('category_id')) has-error @endif">
                       <label for="category_id-field">Category_id</label>
                       {!! Form::select('category_id', $category,old("category_id"),['class' => 'form-control','id'=>'category_id-field']) !!}
                        @if($errors->has("category_id"))
                        <span class="help-block">{{ $errors->first("category_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('mobility_type')) has-error @endif">
                       <label for="mobility_type-field">mobility_type</label>
                       {!! Form::select('mobility_type', ['low'=>'Low','middle'=>'Middle','high'=>'High'],old("mobility_type"),['class' => 'form-control','id'=>'mobility_type-field']) !!}
                        @if($errors->has("mobility_type"))
                        <span class="help-block">{{ $errors->first("mobility_type") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('department_id')) has-error @endif">
                       <label for="department_id-field">Department_id</label>
                       {!! Form::select('department_id', $department,old("department_id"),['class' => 'form-control','id'=>'department_id-field']) !!}
                       @if($errors->has("department_id"))
                        <span class="help-block">{{ $errors->first("department_id") }}</span>
                       @endif
                    </div>

                <div class="form-group @if($errors->has('life')) has-error @endif">
                    <label for="life-field">Life</label>
                    {!! Form::select('life', $life,old("life"),['class' => 'form-control','id'=>'life-field']) !!}
                    @if($errors->has("life"))
                        <span class="help-block">{{ $errors->first("life") }}</span>
                    @endif
                </div>

                    <div class="form-group @if($errors->has('user_id')) has-error @endif">
                       <label for="user_id-field">User_id</label>
                       {!! Form::select('user_id', $member,old("user_id"),['class' => 'form-control','id'=>'user_id-field']) !!}
                       @if($errors->has("user_id"))
                        <span class="help-block">{{ $errors->first("user_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('keterangan')) has-error @endif">
                       <label for="keterangan-field">Notes</label>
                    <textarea class="form-control" id="keterangan-field" rows="3" name="keterangan">{{ old("keterangan") }}</textarea>
                       @if($errors->has("keterangan"))
                        <span class="help-block">{{ $errors->first("keterangan") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('inventories.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
                   format: 'yyyy-mm-dd',
                   todayHighlight: true
    });
  </script>
@endsection

resources/views/inventories/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Inventories / Edit #{{$inventory->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('inventories.update', $inventory->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ is_null(old("name")) ? $inventory->name : old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('description')) has-error @endif">
                       <label for="description-field">Description</label>
                    <input type="text" id="description-field" name="description" class="form-control" value="{{ is_null(old("description")) ? $inventory->description : old("description") }}"/>
                       @if($errors->has("description"))
                        <span class="help-block">{{ $errors->first("description") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('harga_beli')) has-error @endif">
                       <label for="harga_beli-field">Buy Value</label>
                    <input type="numbers" id="harga_beli-field" name="harga_beli" class="form-control" value="{{ is_null(old("harga_beli")) ? $inventory->harga_beli : old("harga_beli") }}"/>
                       @if($errors->has("harga_beli"))
                        <span class="help-block">{{ $errors->first("harga_beli") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('tanggal_beli')) has-error @endif">
                       <label for="tanggal_beli-field">Purchase Date</label>
                    <input type="text" id="tanggal_beli-field" name="tanggal_beli" class="form-control date-picker" value="{{ is_null(old("tanggal_beli")) ? $inventory->tanggal_beli : old("tanggal_beli") }}"/>
                       @if($errors->has("tanggal_beli"))
                        <span class="help-block">{{ $errors->first("tanggal_beli") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('supplier_id')) has-error @endif">
                       <label for="supplier_id-field">Supplier_id</label>
                       {!! Form::select('supplier_id', $supplier,$inventory->supplier_id,['class' => 'form-control','id'=>'supplier_id-field'] !!}
                       @if($errors->has("supplier_id"))
                        <span class="help-block">{{ $errors->first("supplier_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('procurement_id')) has-error @endif">
                       <label for="procurement_id-field">Procurement_id</label>
                       {!! Form::select('procurement_id', $procurement,$inventory->procurement_id,['class' => 'form-control','id'=>'procurement_id-field'] !!}
                       @if($errors->has("procurement_id"))
                        <span class="help-block">{{ $errors->first("procurement_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('category_id')) has-error @endif">
                       <label for="category_id-field">Category_id</label>
                       {!! Form::select('category_id', $category,$inventory->category_id,['class' => 'form-control','id'=>'category_id-field'] !!}
                       @if($errors->has("category_id"))
                        <span class="help-block">{{ $errors->first("category_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('mobility_type')) has-error @endif">
                       <label for="mobility_type-field">mobility_type</label>
                       {!! Form::select('mobility_type', ['low'=>'Low','middle'=>'Middle','high'=>'High'],$inventory->mobility_type,['class' => 'form-control','id'=>'mobility_type-field'] !!}
                       @if($errors->has("mobility_type"))
                        <span class="help-block">{{ $errors->first("mobility_type") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('department_id')) has-error @endif">
                       <label for="department_id-field">Department_id</label>
                       {!! Form::select('department_id', $department,$inventory->department_id,['class' => 'form-control','id'=>'department_id-field'] !!}
                       @if($errors->has("department_id"))
                        <span class="help-block">{{ $errors->first("department_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('user_id')) has-error @endif">
                       <label for="user_id-field">User_id</label>
                       {!! Form::select('user_id', $member,$inventory->user_id,['class' => 'form-control','id'=>'user_id-field'] !!}
                       @if($errors->has("user_id"))
                        <span class="help-block">{{ $errors->first("user_id") }}</span>
                       @endif
                    </div>

                <div class="form-group @if($errors->has('life')) has-error @endif">
                    <label for="life-field">Life</label>
                    {!! Form::select('life', $life,$inventory->life,['class' => 'form-control','id'=>'life-field'] !!}
                    @if($errors->has("life"))
                        <span class="help-block">{{ $errors->first("life") }}</span>
                    @endif
                </div>

                    <div class="form-group @if($errors->has('keterangan')) has-error @endif">
                       <label for="keterangan-field">Notes</label>
                    <textarea class="form-control" id="keterangan-field" rows="3" name="keterangan">{{ is_null(old("keterangan")) ? $inventory->keterangan : old("keterangan") }}</textarea>
                       @if($errors->has("keterangan"))
                        <span class="help-block">{{ $errors->first("keterangan") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('inventories.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
                   format: 'yyyy-mm-dd',
                   todayHighlight: true
    });
  </script>
@endsection

resources/views/inventories/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Inventories / Show #{{$inventory->id}}</h1>
        {{--<form action="{{ route('inventories.destroy', $inventory->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('inventories.edit', $inventory->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>--}}
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="name">NAME</label>
                     <p class="form-control-static">{{$inventory->name}}</p>
                </div>
                    <div class="form-group">
                     <label for="description">DESCRIPTION</label>
                     <p class="form-control-static">{{$inventory->description}}</p>
                </div>
                    <div class="form-group">
                     <label for="harga_beli">BUY VALUE</label>
                     <p class="form-control-static">{{number_format( $inventory->harga_beli , 0 , '.' , ',' )}}</p>
                </div>
                    <div class="form-group">
                     <label for="tanggal_beli">PURCHASE DATE</label>
                     <p class="form-control-static">{{$inventory->tanggal_beli}}</p>
                </div>
                    <div class="form-group">
                     <label for="supplier_id">SUPPLIER_ID</label>
                     <p class="form-control-static">{{$inventory->supp->name}}</p>
                </div>
                    <div class="form-group">
                     <label for="procurement_id">PROCUREMENT_ID</label>
                     <p class="form-control-static">{{$inventory->proc->name}}</p>
                </div>
                    <div class="form-group">
                     <label for="category_id">CATEGORY_ID</label>
                     <p class="form-control-static">{{$inventory->cat->name}}</p>
                </div>
                <div class="form-group">
                     <label for="category_id">MOBILITY TYPE</label>
                     <p class="form-control-static">{{$inventory->mobility_type}}</p>
                </div>
                    <div class="form-group">
                     <label for="department_id">DEPARTMENT_ID</label>
                     <p class="form-control-static">{{$inventory->dept->name}}</p>
                </div>
                    <div class="form-group">
                     <label for="user_id">USER_ID</label>
                     <p class="form-control-static">{{$inventory->member->name}}</p>
                </div>
                    <div class="form-group">
                     <label for="keterangan">NOTES</label>
                     <p class="form-control-static">{{$inventory->keterangan}}</p>
                </div>
                    <div class="form-group">
                     <label for="assets_number">ASSETS_NUMBER</label>
                     <p class="form-control-static">{{$inventory->assets_number}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('inventories.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection