routes/web.php
<?php

use App\Category;
use App\Department;
use App\Inventory;
use App\Member;
use App\Procurement;
use App\Supplier;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::resource("departments","DepartmentController");
Route::resource("suppliers","SupplierController");
Route::resource("members","MemberController");
Route::resource("categories","CategoryController");
Route::resource("procurements","ProcurementController");
Route::resource("inventories","InventoryController");
Route::resource("mutations","MutationController");
Route::resource("reports","ReportController");
Route::get('allassetlistreport', 'AllAssetListReportController@index')->name('allassetlistreport');
Route::get('supplierlistreport', 'SupplierListReportController@index')->name('supplierlistreport');
Route::get('memberlistreport', 'MemberListReportController@index')->name('memberlistreport');
Route::get('assetmutationreport', 'AssetMutationReportController@index')->name('assetmutationreport');
Route::get('assetscrappingreport', 'AssetScrappingReportController@index')->name('assetscrappingreport');
Route::get('assetbalancereport', 'AssetBalanceReportController@index')->name('assetbalancereport');
Route::get('specialassetbasedontypeofmobilityreport', 'SpecialAssetBasedOnTypeOfMobilityReportController@index')->name('specialassetbasedontypeofmobilityreport');
Route::resource("outgoings","OutgoingController"); // Add this line in routes.php

/*
    ___       _____   _  __
   /   |     / /   | | |/ /
  / /| |__  / / /| | |   / 
 / ___ / /_/ / ___ |/   |  
/_/  |_\____/_/  |_/_/|_|  
                           
*/

Route::get('/getAll', function() {

	$inventories = Inventory::all();

	$return = array(
'records' => $inventories,
'query_record_count' => sizeof($inventories),
'total_record_count' => sizeof($inventories)
		);
	// dd($car[0]->store_id);
   return $inventories;
});

Route::get('/getDepartment', function() {

	$departments = Department::all();

	;
	// dd($car[0]->store_id);
   return $departments;
});


Route::get('/getSupplier', function() {

	$suppliers = Supplier::all();

	;
	// dd($car[0]->store_id);
   return $suppliers;
});

Route::get('/getMember', function() {

	$members = Member::all();

	;
	// dd($car[0]->store_id);
   return $members;
});

Route::get('/getCategory', function() {

	$categories = Category::all();

	;
	// dd($car[0]->store_id);
	// dd($categories);
   return $categories;
});

Route::get('/getMobility', function() {

	$mobilities = 
collect(['low'=>'Low','medium'=>'Medium','high'=>'High']);
	// Category::all();

	;
	// dd($mobilities);
	// dd($car[0]->store_id);
   return $mobilities;
});


Route::get('/getProcurement', function() {

	$procurements = Procurement::all();

	;
	// dd($car[0]->store_id);
   return $procurements;
});

app/Procurement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Procurement extends Model
{
    //
}

app/Http/Controllers/ProcurementController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Procurement;
use Illuminate\Http\Request;

class ProcurementController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$procurements = Procurement::orderBy('id', 'desc')->paginate(10);

		return view('procurements.index', compact('procurements'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('procurements.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$procurement = new Procurement();

		$procurement->name = $request->input("name");

		$procurement->save();

		return redirect()->route('procurements.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$procurement = Procurement::findOrFail($id);

		return view('procurements.show', compact('procurement'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$procurement = Procurement::findOrFail($id);

		return view('procurements.edit', compact('procurement'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$procurement = Procurement::findOrFail($id);

		$procurement->name = $request->input("name");

		$procurement->save();

		return redirect()->route('procurements.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$procurement = Procurement::findOrFail($id);
		$procurement->delete();

		return redirect()->route('procurements.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/procurements/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Procurements / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('procurements.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('procurements.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/procurements/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Procurements / Edit #{{$procurement->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('procurements.update', $procurement->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ is_null(old("name")) ? $procurement->name : old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('procurements.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/procurements/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Procurements
            <a class="btn btn-success pull-right" href="{{ route('procurements.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($procurements->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NAME</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($procurements as $procurement)
                            <tr>
                                <td>{{$procurement->id}}</td>
                                <td>{{$procurement->name}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('procurements.show', $procurement->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('procurements.edit', $procurement->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('procurements.destroy', $procurement->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $procurements->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/procurements/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Procurements / Show #{{$procurement->id}}</h1>
        <form action="{{ route('procurements.destroy', $procurement->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('procurements.edit', $procurement->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="name">NAME</label>
                     <p class="form-control-static">{{$procurement->name}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('procurements.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection