routes/web.php
<?php

use App\Category;
use App\Department;
use App\Inventory;
use App\Member;
use App\Procurement;
use App\Supplier;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::resource("departments","DepartmentController");
Route::resource("suppliers","SupplierController");
Route::resource("members","MemberController");
Route::resource("categories","CategoryController");
Route::resource("procurements","ProcurementController");
Route::resource("inventories","InventoryController");
Route::resource("mutations","MutationController");
Route::resource("reports","ReportController");
Route::get('allassetlistreport', 'AllAssetListReportController@index')->name('allassetlistreport');
Route::get('supplierlistreport', 'SupplierListReportController@index')->name('supplierlistreport');
Route::get('memberlistreport', 'MemberListReportController@index')->name('memberlistreport');
Route::get('assetmutationreport', 'AssetMutationReportController@index')->name('assetmutationreport');
Route::get('assetscrappingreport', 'AssetScrappingReportController@index')->name('assetscrappingreport');
Route::get('assetbalancereport', 'AssetBalanceReportController@index')->name('assetbalancereport');
Route::get('specialassetbasedontypeofmobilityreport', 'SpecialAssetBasedOnTypeOfMobilityReportController@index')->name('specialassetbasedontypeofmobilityreport');
Route::resource("outgoings","OutgoingController"); // Add this line in routes.php

/*
    ___       _____   _  __
   /   |     / /   | | |/ /
  / /| |__  / / /| | |   / 
 / ___ / /_/ / ___ |/   |  
/_/  |_\____/_/  |_/_/|_|  
                           
*/

Route::get('/getAll', function() {

	$inventories = Inventory::all();

	$return = array(
'records' => $inventories,
'query_record_count' => sizeof($inventories),
'total_record_count' => sizeof($inventories)
		);
	// dd($car[0]->store_id);
   return $inventories;
});

Route::get('/getDepartment', function() {

	$departments = Department::all();

	;
	// dd($car[0]->store_id);
   return $departments;
});


Route::get('/getSupplier', function() {

	$suppliers = Supplier::all();

	;
	// dd($car[0]->store_id);
   return $suppliers;
});

Route::get('/getMember', function() {

	$members = Member::all();

	;
	// dd($car[0]->store_id);
   return $members;
});

Route::get('/getCategory', function() {

	$categories = Category::all();

	;
	// dd($car[0]->store_id);
	// dd($categories);
   return $categories;
});

Route::get('/getMobility', function() {

	$mobilities = 
collect(['low'=>'Low','medium'=>'Medium','high'=>'High']);
	// Category::all();

	;
	// dd($mobilities);
	// dd($car[0]->store_id);
   return $mobilities;
});


Route::get('/getProcurement', function() {

	$procurements = Procurement::all();

	;
	// dd($car[0]->store_id);
   return $procurements;
});

app/Outgoing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Outgoing extends Model
{

    public function inv()
    {
        return $this->hasOne('App\Inventory', 'id', 'inventory_id');
    }


}

app/Http/Controllers/OutgoingController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Inventory;
use App\Outgoing;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Maatwebsite\Excel\Facades\Excel;

class OutgoingController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
	    if(Input::get('print'))
        {
            if(Input::get('print')=='true')
            {
                $outgoings = Outgoing::orderBy('id', 'desc')->get();
                Excel::create('outgoings', function($excel) use($outgoings) {
                    $excel->sheet('Sheet 1', function($sheet) use($outgoings) {
                        $sheet->fromArray($outgoings);
                    });
                })->export('xls');
            }

        }
        else
        {
            $outgoings = Outgoing::orderBy('id', 'desc')->paginate(10);

            return view('outgoings.index', compact('outgoings'));
        }

	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        $inventory = Inventory::where('status',1)->pluck('assets_number','id');
        return view('outgoings.create',compact('inventory'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$outgoing = new Outgoing();

		$outgoing->inventory_id = $request->input("inventory_id");
        $outgoing->keterangan = $request->input("keterangan");

        $inventory = Inventory::find($request->input('inventory_id'));
        $inventory->status = 0;
        $inventory->save();

		$outgoing->save();

		return redirect()->route('outgoings.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$outgoing = Outgoing::findOrFail($id);

		return view('outgoings.show', compact('outgoing'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$outgoing = Outgoing::findOrFail($id);

		return view('outgoings.edit', compact('outgoing'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$outgoing = Outgoing::findOrFail($id);

		$outgoing->inventory_id = $request->input("inventory_id");
        $outgoing->keterangan = $request->input("keterangan");

		$outgoing->save();

		return redirect()->route('outgoings.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$outgoing = Outgoing::findOrFail($id);
		$outgoing->delete();

		return redirect()->route('outgoings.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/outgoings/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Outgoings / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('outgoings.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('inventory_id')) has-error @endif">
                       <label for="inventory_id-field">Inventory_id</label>
                    {!! Form::select('inventory_id', $inventory,old("inventory_id"),['class' => 'form-control','class'=>'form-control','id'=>'inventory_id-field']); !!}
                       @if($errors->has("inventory_id"))
                        <span class="help-block">{{ $errors->first("inventory_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('keterangan')) has-error @endif">
                       <label for="keterangan-field">Notes</label>
                    <input type="text" id="keterangan-field" name="keterangan" class="form-control" value="{{ old("keterangan") }}"/>
                       @if($errors->has("keterangan"))
                        <span class="help-block">{{ $errors->first("keterangan") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('outgoings.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/outgoings/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Outgoings / Edit #{{$outgoing->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('outgoings.update', $outgoing->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('inventory_id')) has-error @endif">
                       <label for="inventory_id-field">Inventory_id</label>
                    <input type="text" id="inventory_id-field" name="inventory_id" class="form-control" value="{{ is_null(old("inventory_id")) ? $outgoing->inventory_id : old("inventory_id") }}"/>
                       @if($errors->has("inventory_id"))
                        <span class="help-block">{{ $errors->first("inventory_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('keterangan')) has-error @endif">
                       <label for="keterangan-field">Notes</label>
                    <input type="text" id="keterangan-field" name="keterangan" class="form-control" value="{{ is_null(old("keterangan")) ? $outgoing->keterangan : old("keterangan") }}"/>
                       @if($errors->has("keterangan"))
                        <span class="help-block">{{ $errors->first("keterangan") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('outgoings.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/outgoings/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Outgoings
            <a class="btn btn-success pull-right" href="{{ route('outgoings.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($outgoings->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>INVENTORY_NAME</th>
                            <th>PURCHASE_DATE</th>
                            <th>NOTES</th>
                           {{-- <th class="text-right">OPTIONS</th>--}}
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($outgoings as $outgoing)
                            <tr>
                                <td>{{$outgoing->id}}</td>
                                <td>ID: {{$outgoing->inv->id}} - Name: {{$outgoing->inv->name}} - Assets Number: {{$outgoing->inv->assets_number}}</td>
                                <td>Date: {{$outgoing->inv->tanggal_beli}}</td>
                    <td>{{$outgoing->keterangan}}</td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $outgoings->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/outgoings/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Outgoings / Show #{{$outgoing->id}}</h1>
        <form action="{{ route('outgoings.destroy', $outgoing->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('outgoings.edit', $outgoing->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="inventory_id">INVENTORY_ID</label>
                     <p class="form-control-static">{{$outgoing->inventory_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="keterangan">NOTES</label>
                     <p class="form-control-static">{{$outgoing->keterangan}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('outgoings.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection